#!/usr/bin/env python3
"""TradeYantra tenant provisioner (Phase 2 prototype).

Automates the manual concierge runbook: allocate ports, render a per-tenant
`.env`, bring the instance up with Docker Compose, health-check it, and record it
in a JSON registry. One isolated TradeYantra instance per tenant.

This is a PROTOTYPE/scaffold — stdlib only, JSON registry, Docker backend. For
production, swap the JSON registry for Postgres, add a static-IP-per-tenant step,
secrets manager, and real monitoring (see ../../SAAS_ROADMAP.md).

Usage:
    python provision.py create acme --broker zerodha --domain acme.tradeyantra.in \
        --api-key KEY --api-secret SECRET [--dry-run]
    python provision.py suspend acme [--dry-run]
    python provision.py resume  acme [--dry-run]
    python provision.py destroy acme [--dry-run]
    python provision.py list
    python provision.py show acme

Run with --dry-run to see exactly what would happen without Docker installed.
"""
from __future__ import annotations

import argparse
import json
import re
import secrets
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]                      # .../Algo-SaaS
SAMPLE_ENV = REPO_ROOT / ".sample.env"
REGISTRY = HERE / "tenants.json"
TENANTS_DIR = HERE / "tenants"

# Port bases mirror install-multi.sh: instance i gets base + (i-1).
FLASK_BASE, WS_BASE, ZMQ_BASE = 5000, 8765, 5555
IMAGE = "tradeyantra:latest"                      # build once: docker build -t tradeyantra .

# Caddy reverse proxy: one generated snippet per tenant, imported by the master
# Caddyfile. The provisioner writes/removes snippets and reloads Caddy.
CADDY_DIR = HERE / "caddy"
CADDY_TENANTS = CADDY_DIR / "tenants"
CADDY_MASTER = CADDY_DIR / "Caddyfile"


# ---------- registry ----------
def load_registry() -> dict:
    if REGISTRY.exists():
        return json.loads(REGISTRY.read_text())
    return {"tenants": []}


def save_registry(reg: dict) -> None:
    REGISTRY.write_text(json.dumps(reg, indent=2) + "\n", encoding="utf-8")


def find(reg: dict, tid: str) -> dict | None:
    return next((t for t in reg["tenants"] if t["id"] == tid), None)


def next_index(reg: dict) -> int:
    """Lowest positive slot not in use, so destroyed slots get reused."""
    used = {t["index"] for t in reg["tenants"]}
    i = 1
    while i in used:
        i += 1
    return i


# ---------- env rendering ----------
def set_env(text: str, key: str, value: str) -> str:
    """Replace the whole `KEY = '...'` / `KEY='...'` line; append if absent."""
    pattern = re.compile(rf"^{re.escape(key)}\s*=.*$", re.MULTILINE)
    line = f"{key} = '{value}'"
    if pattern.search(text):
        return pattern.sub(line, text)
    return text.rstrip() + "\n" + line + "\n"


def render_env(t: dict) -> str:
    if not SAMPLE_ENV.exists():
        sys.exit(f"ERROR: {SAMPLE_ENV} not found — run from inside the repo.")
    env = SAMPLE_ENV.read_text()
    dom, br, i = t["domain"], t["broker"], t["index"]

    env = set_env(env, "BROKER_API_KEY", t["api_key"])
    env = set_env(env, "BROKER_API_SECRET", t["api_secret"])
    env = set_env(env, "REDIRECT_URL", f"https://{dom}/{br}/callback")
    env = set_env(env, "HOST_SERVER", f"https://{dom}")
    env = set_env(env, "CORS_ALLOWED_ORIGINS", f"https://{dom}")
    env = set_env(env, "WEBSOCKET_URL", f"wss://{dom}/ws")
    # Per-tenant secrets (unique crypto material per instance).
    env = set_env(env, "APP_KEY", secrets.token_hex(32))
    env = set_env(env, "API_KEY_PEPPER", secrets.token_hex(32))
    env = set_env(env, "FERNET_SALT", secrets.token_hex(32))
    # Ports (unique per tenant).
    env = set_env(env, "FLASK_PORT", str(t["flask_port"]))
    env = set_env(env, "WEBSOCKET_PORT", str(t["ws_port"]))
    env = set_env(env, "ZMQ_PORT", str(t["zmq_port"]))
    # In a container the app must bind all interfaces so the host can reach it.
    env = set_env(env, "FLASK_HOST_IP", "0.0.0.0")
    # Per-tenant database files (full isolation).
    env = set_env(env, "DATABASE_URL", f"sqlite:///db/openalgo{i}.db")
    env = set_env(env, "LATENCY_DATABASE_URL", f"sqlite:///db/latency{i}.db")
    env = set_env(env, "LOGS_DATABASE_URL", f"sqlite:///db/logs{i}.db")
    env = set_env(env, "HEALTH_DATABASE_URL", f"sqlite:///db/health{i}.db")
    env = set_env(env, "SANDBOX_DATABASE_URL", f"sqlite:///db/sandbox{i}.db")
    env = set_env(env, "HISTORIFY_DATABASE_URL", f"db/historify{i}.duckdb")
    return env


def render_compose(t: dict) -> str:
    fp, wp = t["flask_port"], t["ws_port"]
    return f"""# Generated by provision.py - tenant {t['id']}
services:
  app:
    image: {IMAGE}
    container_name: ty-{t['id']}
    restart: unless-stopped
    env_file: .env
    # Publish only on localhost; the shared Caddy proxy routes {t['domain']}
    # -> flask {fp} (HTTP + socket.io) and /ws -> {wp}. Never expose publicly.
    ports:
      - "127.0.0.1:{fp}:{fp}"
      - "127.0.0.1:{wp}:{wp}"
    volumes:
      - tenant_db:/app/db
volumes:
  tenant_db:
"""


def render_caddy(t: dict) -> str:
    """Caddy site block: subdomain -> tenant ports, auto-TLS, WebSocket-aware."""
    return f"""# Generated by provision.py - tenant {t['id']}
{t['domain']} {{
\t# Market-data WebSocket proxy server runs on its own port.
\t@ws path /ws /ws/*
\treverse_proxy @ws 127.0.0.1:{t['ws_port']}
\t# Everything else (UI, REST API, Socket.IO) -> the Flask app.
\treverse_proxy 127.0.0.1:{t['flask_port']}
}}
"""


def reload_caddy(dry: bool) -> None:
    """Best-effort Caddy reload; a missing Caddy binary must not fail provisioning."""
    cmd = ["caddy", "reload", "--config", str(CADDY_MASTER)]
    if dry:
        print("   would run:", " ".join(cmd))
        return
    try:
        subprocess.run(cmd, check=True, cwd=str(CADDY_DIR))
        print("   reloaded Caddy")
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"   WARN: Caddy reload skipped ({e}). Run "
              f"'caddy reload --config {CADDY_MASTER}' once Caddy is up.")


# ---------- backend ----------
def run(cmd: list[str], dry: bool) -> None:
    if dry:
        print("   would run:", " ".join(cmd))
        return
    subprocess.run(cmd, check=True)


def compose(t: dict, *args: str) -> list[str]:
    d = TENANTS_DIR / t["id"]
    return ["docker", "compose", "-f", str(d / "docker-compose.yml"),
            "-p", f"ty-{t['id']}", *args]


def health_check(port: int, dry: bool) -> bool:
    if dry:
        print(f"   would health-check http://127.0.0.1:{port}/")
        return True
    for _ in range(30):
        try:
            with urlopen(f"http://127.0.0.1:{port}/", timeout=2) as r:
                if r.status in (200, 302):
                    return True
        except (URLError, OSError):
            pass
    return False


# ---------- commands ----------
def cmd_create(a) -> None:
    reg = load_registry()
    if find(reg, a.tenant):
        sys.exit(f"ERROR: tenant '{a.tenant}' already exists.")
    i = next_index(reg)
    t = {
        "id": a.tenant,
        "domain": a.domain or f"{a.tenant}.tradeyantra.in",
        "broker": a.broker,
        "api_key": a.api_key or "SET_ME",
        "api_secret": a.api_secret or "SET_ME",
        "index": i,
        "flask_port": FLASK_BASE + i - 1,
        "ws_port": WS_BASE + i - 1,
        "zmq_port": ZMQ_BASE + i - 1,
        "status": "provisioning",
        "created_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    print(f"==> Provisioning '{t['id']}'  domain={t['domain']}  "
          f"ports(flask/ws/zmq)={t['flask_port']}/{t['ws_port']}/{t['zmq_port']}")

    d = TENANTS_DIR / t["id"]
    snippet = CADDY_TENANTS / f"{t['id']}.caddy"
    if a.dry_run:
        print(f"   would write {d}/.env  and  {d}/docker-compose.yml")
        print(f"   would write {snippet}  (routes {t['domain']})")
    else:
        d.mkdir(parents=True, exist_ok=True)
        (d / ".env").write_text(render_env(t), encoding="utf-8")
        (d / "docker-compose.yml").write_text(render_compose(t), encoding="utf-8")
        CADDY_TENANTS.mkdir(parents=True, exist_ok=True)
        snippet.write_text(render_caddy(t), encoding="utf-8")
        print(f"   wrote {d}/.env (+ docker-compose.yml) and Caddy snippet")

    run(compose(t, "up", "-d"), a.dry_run)
    reload_caddy(a.dry_run)

    if health_check(t["flask_port"], a.dry_run):
        t["status"] = "running"
        print(f"==> READY: https://{t['domain']}  (set broker redirect to "
              f"https://{t['domain']}/{t['broker']}/callback)")
    else:
        t["status"] = "unhealthy"
        print("==> WARNING: health check failed — inspect the container logs.")

    # Record even in dry-run so `list` shows the plan; mark it.
    if a.dry_run:
        t["status"] = "dry-run"
    reg["tenants"].append(t)
    save_registry(reg)


def _lifecycle(a, action: str, new_status: str, *compose_args: str) -> None:
    reg = load_registry()
    t = find(reg, a.tenant)
    if not t:
        sys.exit(f"ERROR: no tenant '{a.tenant}'.")
    print(f"==> {action} '{t['id']}'")
    run(compose(t, *compose_args), a.dry_run)
    if not a.dry_run:
        t["status"] = new_status
        save_registry(reg)


def cmd_suspend(a):
    _lifecycle(a, "Suspending", "suspended", "stop")


def cmd_resume(a):
    _lifecycle(a, "Resuming", "running", "start")


def cmd_destroy(a):
    reg = load_registry()
    t = find(reg, a.tenant)
    if not t:
        sys.exit(f"ERROR: no tenant '{a.tenant}'.")
    print(f"==> Destroying '{t['id']}' (snapshot db/ first in production!)")
    run(compose(t, "down", "-v"), a.dry_run)
    snippet = CADDY_TENANTS / f"{t['id']}.caddy"
    if a.dry_run:
        print(f"   would remove {snippet}")
    elif snippet.exists():
        snippet.unlink()
        print("   removed Caddy snippet")
    reload_caddy(a.dry_run)
    if not a.dry_run:
        reg["tenants"] = [x for x in reg["tenants"] if x["id"] != a.tenant]
        save_registry(reg)
        print("   removed from registry.")


def cmd_list(a):
    reg = load_registry()
    if not reg["tenants"]:
        print("(no tenants)")
        return
    print(f"{'TENANT':<16}{'STATUS':<13}{'FLASK':<7}{'DOMAIN'}")
    for t in sorted(reg["tenants"], key=lambda x: x["index"]):
        print(f"{t['id']:<16}{t['status']:<13}{t['flask_port']:<7}{t['domain']}")


def cmd_show(a):
    t = find(load_registry(), a.tenant)
    if not t:
        sys.exit(f"ERROR: no tenant '{a.tenant}'.")
    print(json.dumps(t, indent=2))


# ---------- cli ----------
def main() -> None:
    p = argparse.ArgumentParser(description="TradeYantra tenant provisioner (prototype)")
    sub = p.add_subparsers(dest="cmd", required=True)

    c = sub.add_parser("create", help="provision a new tenant instance")
    c.add_argument("tenant")
    c.add_argument("--broker", default="zerodha")
    c.add_argument("--domain", default=None, help="default: <tenant>.tradeyantra.in")
    c.add_argument("--api-key", dest="api_key", default=None)
    c.add_argument("--api-secret", dest="api_secret", default=None)
    c.add_argument("--dry-run", action="store_true")
    c.set_defaults(func=cmd_create)

    for name, fn in (("suspend", cmd_suspend), ("resume", cmd_resume), ("destroy", cmd_destroy)):
        s = sub.add_parser(name, help=f"{name} a tenant")
        s.add_argument("tenant")
        s.add_argument("--dry-run", action="store_true")
        s.set_defaults(func=fn)

    sub.add_parser("list", help="list all tenants").set_defaults(func=cmd_list)
    sh = sub.add_parser("show", help="show one tenant's record")
    sh.add_argument("tenant")
    sh.set_defaults(func=cmd_show)

    a = p.parse_args()
    a.func(a)


if __name__ == "__main__":
    main()
